from __future__ import annotations

import os
from datetime import datetime, timezone
from typing import Any

import psycopg
from dotenv import find_dotenv, load_dotenv
from psycopg.rows import dict_row

from .models import (
    CategoriaObjeto,
    MensagemAtualizacao,
    MensagemCriacao,
    MensagemResposta,
    ObjetoAtualizado,
    ObjetoCriacao,
    ObjetoResposta,
)

load_dotenv(find_dotenv())


def _get_database_url() -> str:
    database_url = os.getenv("DATABASE_URL") or os.getenv("database")
    if not database_url:
        raise RuntimeError(
            "Configure DATABASE_URL (ou database) no arquivo .env com a URL do Neon."
        )
    return database_url


def get_connection() -> psycopg.Connection[dict[str, Any]]:
    return psycopg.connect(
        _get_database_url(),
        row_factory=dict_row,
        connect_timeout=10,
    )


def initialize_database() -> None:
    """Cria as tabelas no PostgreSQL/Neon quando ainda não existirem."""
    with get_connection() as connection:
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS objetos (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                autor VARCHAR(50) NOT NULL,
                nome VARCHAR(100) NOT NULL,
                descricao VARCHAR(500) NOT NULL,
                categoria VARCHAR(30) NOT NULL,
                imagem_url TEXT NOT NULL,
                curtidas INTEGER NOT NULL DEFAULT 0 CHECK (curtidas >= 0),
                criado_em TIMESTAMPTZ NOT NULL,
                atualizado_em TIMESTAMPTZ NOT NULL
            )
            """
        )
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS mensagens (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                autor VARCHAR(50) NOT NULL,
                conteudo VARCHAR(1000) NOT NULL,
                criado_em TIMESTAMPTZ NOT NULL,
                atualizado_em TIMESTAMPTZ NOT NULL
            )
            """
        )


def _row_to_obj(row: dict[str, Any]) -> ObjetoResposta:
    return ObjetoResposta(
        id=row["id"],
        autor=row["autor"],
        nome=row["nome"],
        descricao=row["descricao"],
        categoria=row["categoria"],
        imagem_url=row["imagem_url"],
        curtidas=row["curtidas"],
    )


def _now() -> datetime:
    return datetime.now(timezone.utc)


def list_objetos(limit: int = 100, offset: int = 0) -> list[ObjetoResposta]:
    with get_connection() as connection:
        rows = connection.execute(
            "SELECT * FROM objetos ORDER BY criado_em DESC LIMIT %s OFFSET %s",
            (limit, offset),
        ).fetchall()
    return [_row_to_obj(row) for row in rows]


def get_objeto(objeto_id: int) -> ObjetoResposta | None:
    with get_connection() as connection:
        row = connection.execute(
            "SELECT * FROM objetos WHERE id = %s", (objeto_id,)
        ).fetchone()
    return _row_to_obj(row) if row is not None else None


def create_objeto(objeto: ObjetoCriacao) -> ObjetoResposta:
    created_at = _now()
    with get_connection() as connection:
        row = connection.execute(
            """
            INSERT INTO objetos (
                autor, nome, descricao, categoria, imagem_url,
                curtidas, criado_em, atualizado_em
            )
            VALUES (%s, %s, %s, %s, %s, 0, %s, %s)
            RETURNING *
            """,
            (
                objeto.autor,
                objeto.nome,
                objeto.descricao,
                objeto.categoria,
                str(objeto.imagem_url),
                created_at,
                created_at,
            ),
        ).fetchone()
    return _row_to_obj(row)


def update_objeto(objeto_id: int, dados: ObjetoAtualizado) -> ObjetoResposta | None:
    updates: dict[str, object] = {}
    if dados.nome is not None:
        updates["nome"] = dados.nome
    if dados.descricao is not None:
        updates["descricao"] = dados.descricao
    if dados.categoria is not None:
        updates["categoria"] = dados.categoria
    if dados.imagem_url is not None:
        updates["imagem_url"] = str(dados.imagem_url)

    if not updates:
        return get_objeto(objeto_id)

    updates["atualizado_em"] = _now()
    set_clause = ", ".join(f"{campo} = %s" for campo in updates)
    values = [*updates.values(), objeto_id]
    with get_connection() as connection:
        row = connection.execute(
            f"UPDATE objetos SET {set_clause} WHERE id = %s RETURNING *", values
        ).fetchone()
    return _row_to_obj(row) if row is not None else None


def delete_objeto(objeto_id: int) -> bool:
    with get_connection() as connection:
        cursor = connection.execute(
            "DELETE FROM objetos WHERE id = %s", (objeto_id,)
        )
    return cursor.rowcount > 0


def like_objeto(objeto_id: int) -> ObjetoResposta | None:
    with get_connection() as connection:
        row = connection.execute(
            """
            UPDATE objetos
            SET curtidas = curtidas + 1, atualizado_em = %s
            WHERE id = %s
            RETURNING *
            """,
            (_now(), objeto_id),
        ).fetchone()
    return _row_to_obj(row) if row is not None else None


def get_categorias() -> list[CategoriaObjeto]:
    return list(CategoriaObjeto.__args__)


def _row_to_mensagem(row: dict[str, Any]) -> MensagemResposta:
    return MensagemResposta(
        id=row["id"],
        autor=row["autor"],
        conteudo=row["conteudo"],
        criado_em=row["criado_em"],
        atualizado_em=row["atualizado_em"],
    )


def list_mensagens(limit: int = 100, offset: int = 0) -> list[MensagemResposta]:
    with get_connection() as connection:
        rows = connection.execute(
            "SELECT * FROM mensagens ORDER BY criado_em DESC LIMIT %s OFFSET %s",
            (limit, offset),
        ).fetchall()
    return [_row_to_mensagem(row) for row in rows]


def get_mensagem(mensagem_id: int) -> MensagemResposta | None:
    with get_connection() as connection:
        row = connection.execute(
            "SELECT * FROM mensagens WHERE id = %s", (mensagem_id,)
        ).fetchone()
    return _row_to_mensagem(row) if row is not None else None


def create_mensagem(mensagem: MensagemCriacao) -> MensagemResposta:
    created_at = _now()
    with get_connection() as connection:
        row = connection.execute(
            """
            INSERT INTO mensagens (autor, conteudo, criado_em, atualizado_em)
            VALUES (%s, %s, %s, %s)
            RETURNING *
            """,
            (mensagem.autor, mensagem.conteudo, created_at, created_at),
        ).fetchone()
    return _row_to_mensagem(row)


def update_mensagem(
    mensagem_id: int, dados: MensagemAtualizacao
) -> MensagemResposta | None:
    updates = dados.model_dump(exclude_none=True)
    if not updates:
        return get_mensagem(mensagem_id)

    updates["atualizado_em"] = _now()
    set_clause = ", ".join(f"{campo} = %s" for campo in updates)
    values = [*updates.values(), mensagem_id]
    with get_connection() as connection:
        row = connection.execute(
            f"UPDATE mensagens SET {set_clause} WHERE id = %s RETURNING *", values
        ).fetchone()
    return _row_to_mensagem(row) if row is not None else None


def delete_mensagem(mensagem_id: int) -> bool:
    with get_connection() as connection:
        cursor = connection.execute(
            "DELETE FROM mensagens WHERE id = %s", (mensagem_id,)
        )
    return cursor.rowcount > 0
